services:
  app:
    build: .
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
      - "8090:5005"
  mongodb:
    image: mongo
    hostname: mongodb
    ports:
      - "27017:27017"
